# Generated by Django 4.2.27 on 2026-01-10 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('service_type', models.CharField(choices=[('consultation', 'Консультация'), ('outsourcing', 'Правовой аутсорсинг'), ('contract', 'Проверка договора'), ('crisis', 'Антикризисное управление')], max_length=50, verbose_name='Тип услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('awaiting_payment', 'Ожидает оплаты'), ('in_progress', 'В работе'), ('completed', 'Завершен')], default='pending', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
