# Generated by Django 4.2.27 on 2026-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company_name_user_inn_user_kpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('lawyer', 'Юрист'), ('admin', 'Администратор'), ('content_manager', 'Контент-менеджер'), ('director', 'Руководитель')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
